@taskkill /fi "WINDOWTITLE eq StateCenter"
@taskkill /fi "WINDOWTITLE eq Worker:8001"
@taskkill /fi "WINDOWTITLE eq Worker:8002"
@taskkill /fi "WINDOWTITLE eq Merger"
@taskkill /fi "WINDOWTITLE eq Cacher"